### ISSUE TITLE
GravityChanger 1.18.2 (From the mod's Git) crashes Minecraft

### ISSUE THREAD

**Issue by Ujjwal-Rohilla** [qouteall/GravityChanger#2]
### **Version**
Minecraft Version: 1.18.2
GravityChanger Mod Version: 0.3.1
Immersive Portal Version: 1.3.6

### **Steps to reproduce**
Adding GravityChanger mod to mods folder crashes Minecraft when started

### **Mods in Mod Folder (Excluding GravityChanger)**
Note: Minecraft works without GravityChanger
![image](https://user-images.githubusercontent.com/74773615/164977606-da3513bb-5bad-482b-9d9b-8d1903a92cdf.png)

### **Crash Report**
```
Picked up _JAVA_OPTIONS: 
[16:41:14] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[16:41:15] [main/WARN]: Warnings were found!
 - Mod 'DeathLog' (deathlog) 0.2.7+1.18 recommends version 3.1.0 or later of trinkets, which is missing!
	 - You should install version 3.1.0 or later of trinkets for the optimal experience.
 - Mod 'Reese's Sodium Options' (reeses-sodium-options) 1.4.2 recommends version 0.4.2 or later of sodium-extra, which is missing!
	 - You should install version 0.4.2 or later of sodium-extra for the optimal experience.
[16:41:15] [main/INFO]: Loading 138 mods:
	- advanced_runtime_resource_pack 0.5.5 via enhancedblockentities
	- advancementinfo 1.18.2-fabric0.47.10-1.3.1
	- betterf3 1.2.4
	- cameraoverhaul 1.3.0-fabric-universal
	- camerautils 1.18.2-1.0.0
	- citresewn 1.0.1+1.18.2
	- citresewn-defaults 1.0.1+1.18.2 via citresewn
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57 via betterf3
	- com_github_llamalad7_mixinextras 0.0.6 via evergreenhud
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- commons-codec_commons-codec 1.10 via evergreenhud
	- commons-logging_commons-logging 1.2 via evergreenhud
	- deathlog 0.2.7+1.18
	- dev_isxander_settxi 2.1.0 via evergreenhud
	- dynamicfps 2.1.0
	- elementa 427 via evergreenhud
	- enhanced_attack_indicator 1.0.3+1.18
	- enhancedblockentities 0.6+1.18.2
	- evergreenhud 2.0.0-alpha.6
	- fabric 0.51.1+1.18.2
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 2.0.0+1.18.2-SNAPSHOT via inspecio
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.13.3
	- fabrishot ${version}
	- fpsdisplay 1.5.0+1.18.2
	- freelook 1.1.1
	- gravitychanger 0.3.1
	- imm_ptl_core 1.3.6 via immersive_portals
	- immersive_portals 1.3.6
	- indium 1.0.2+mc1.18.2
	- inspecio 1.3.0+1.18
	- inventoryprofilesnext 1.3.5
	- io_ktor_ktor-client-apache-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-client-content-negotiation-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-client-core-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-events-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-http-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-io-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-serialization-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-serialization-kotlinx-json-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-serialization-kotlinx-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-utils-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-websocket-serialization-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-websockets-jvm 2.0.0-beta-1 via evergreenhud
	- iris 1.2.2-build.32
	- java 17
	- kanos_config 0.2.0+1.14.4-1.19 via pehkui
	- krypton 0.1.9
	- lambdynlights 2.1.0+1.17
	- lazydfu 0.1.2
	- lithium 0.7.9
	- minecraft 1.18.2
	- modmanager 1.2.3+1.18
	- modmenu 3.1.1
	- org_anarres_jcpp 1.4.14 via iris
	- org_apache_httpcomponents_httpasyncclient 4.1.4 via evergreenhud
	- org_apache_httpcomponents_httpclient 4.5.6 via evergreenhud
	- org_apache_httpcomponents_httpcore 4.4.14 via evergreenhud
	- org_apache_httpcomponents_httpcore-nio 4.4.14 via evergreenhud
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_bundleproject_libversion 0.0.3 via evergreenhud
	- org_commonmark_commonmark 0.17.1 via evergreenhud
	- org_commonmark_commonmark-ext-gfm-strikethrough 0.17.1 via evergreenhud
	- org_commonmark_commonmark-ext-ins 0.17.1 via evergreenhud
	- org_dom4j_dom4j 2.1.1 via evergreenhud
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- pehkui 3.2.2+1.14.4-1.19
	- phosphor 0.8.1
	- pride 1.1.0+1.17 via lambdynlights
	- q_misc_util 1.3.6 via immersive_portals
	- quilt_base 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-api-base
	- quilt_client_command 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-command-api-v1
	- quilt_command 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-command-api-v1
	- quilt_lifecycle_events 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-lifecycle-events-v1
	- quilt_resource_loader 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-resource-loader-v0
	- quilt_tags 1.0.0+1.18.2-SNAPSHOT via inspecio
	- quilt_tooltip 1.0.0+1.18.2-SNAPSHOT via fabric-rendering-v1
	- quilted-fabric-api-base 1.0.0+1.18.2-SNAPSHOT via inspecio
	- quilted-fabric-command-api-v1 2.0.0+1.18.2-SNAPSHOT via inspecio
	- quilted-fabric-lifecycle-events-v1 2.0.1+1.18.2-SNAPSHOT via inspecio
	- quilted-fabric-resource-loader-v0 1.0.0+1.18.2-SNAPSHOT via inspecio
	- reeses-sodium-options 1.4.2
	- sodium 0.4.1+build.15
	- sound_physics_remastered 1.18.2-1.0.5
	- spruceui 3.3.0+1.17 via enhancedblockentities
	- statuseffecttimer 1.1.0+1.18.1
	- universalcraft 1.0.0 via evergreenhud
	- voicechat 1.18.2-2.2.36
	- wthit 4.8.1
	- wthit-plugins 1.0.4
[16:41:15] [main/WARN]: Mod `fabrishot` (${version}) does not respect SemVer - comparison support is limited.
[16:41:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/rohil/AppData/Roaming/.tlauncher/legacy/Minecraft/files/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[16:41:15] [main/INFO]: Compatibility level set to JAVA_17
[16:41:15] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 1 override(s) found
[16:41:15] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[16:41:15] [main/INFO]: Using modern mixin 'mirsario.cameraoverhaul.fabric.mixins.modern.CameraMixin'.
[16:41:15] [main/INFO]: Using modern mixin 'mirsario.cameraoverhaul.fabric.mixins.modern.GameRendererMixin'.
[16:41:15] [main/INFO]: Skipping legacy mixin 'mirsario.cameraoverhaul.fabric.mixins.legacy.LegacyCameraMixin'.
[16:41:16] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [immersive_portals, krypton]) disables it and children
[16:41:16] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[16:41:16] [main/INFO]: I used the json to destroy the json
[16:41:17] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[16:41:17] [DefaultDispatcher-worker-1/INFO]: Checking for mod updates...
[16:41:18] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen should be final
[16:41:18] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen should be final
[16:41:18] [main/ERROR]: Mixin apply for mod gravitychanger failed gravitychanger.mixins.json:EntityMixin -> net.minecraft.class_1297: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1297::redirect_adjustMovementForCollisions_adjustMovementForCollisions_0 with priority 1000 cannot inject into net/minecraft/class_1297::method_20736(Lnet/minecraft/class_1297;Lnet/minecraft/class_243;Lnet/minecraft/class_238;Lnet/minecraft/class_1937;Ljava/util/List;)Lnet/minecraft/class_243; merged by me.jellysquid.mods.lithium.mixin.entity.collisions.movement.EntityMixin with priority 1000 [PREINJECT Applicator Phase -> gravitychanger.mixins.json:EntityMixin -> Prepare Injections ->  -> redirect$zkh000$redirect_adjustMovementForCollisions_adjustMovementForCollisions_0(Lnet/minecraft/class_243;Lnet/minecraft/class_238;Ljava/util/List;Lnet/minecraft/class_1297;)Lnet/minecraft/class_243; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1297::redirect_adjustMovementForCollisions_adjustMovementForCollisions_0 with priority 1000 cannot inject into net/minecraft/class_1297::method_20736(Lnet/minecraft/class_1297;Lnet/minecraft/class_243;Lnet/minecraft/class_238;Lnet/minecraft/class_1937;Ljava/util/List;)Lnet/minecraft/class_243; merged by me.jellysquid.mods.lithium.mixin.entity.collisions.movement.EntityMixin with priority 1000 [PREINJECT Applicator Phase -> gravitychanger.mixins.json:EntityMixin -> Prepare Injections ->  -> redirect$zkh000$redirect_adjustMovementForCollisions_adjustMovementForCollisions_0(Lnet/minecraft/class_243;Lnet/minecraft/class_238;Ljava/util/List;Lnet/minecraft/class_1297;)Lnet/minecraft/class_243; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) [client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
[16:41:18] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1297 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1297 failed
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[Fabric%201.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1297 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[Fabric%201.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[Fabric%201.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [gravitychanger.mixins.json:EntityMixin] from phase [DEFAULT] in config [gravitychanger.mixins.json] from mod [gravitychanger] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[Fabric%201.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1297::redirect_adjustMovementForCollisions_adjustMovementForCollisions_0 with priority 1000 cannot inject into net/minecraft/class_1297::method_20736(Lnet/minecraft/class_1297;Lnet/minecraft/class_243;Lnet/minecraft/class_238;Lnet/minecraft/class_1937;Ljava/util/List;)Lnet/minecraft/class_243; merged by me.jellysquid.mods.lithium.mixin.entity.collisions.movement.EntityMixin with priority 1000 [PREINJECT Applicator Phase -> gravitychanger.mixins.json:EntityMixin -> Prepare Injections ->  -> redirect$zkh000$redirect_adjustMovementForCollisions_adjustMovementForCollisions_0(Lnet/minecraft/class_243;Lnet/minecraft/class_238;Ljava/util/List;Lnet/minecraft/class_1297;)Lnet/minecraft/class_243; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[Fabric%201.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
```

**Comment by PitchBlackNights** [comment]
Remove CameraOverhaul

**Comment by Ujjwal-Rohilla** [comment]
Oh... yeah that works... damn thanks
